# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'f30' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for f30

  pod 'Firebase/Core', inhibit_warnings: true
  pod ‘Firebase/Database’, inhibit_warnings: true
  pod ‘Firebase/Storage’, inhibit_warnings: true
  pod 'Firebase/Auth', inhibit_warnings: true
  pod 'TwitterKit', inhibit_warnings: true
  pod 'FBSDKCoreKit', inhibit_warnings: true
  pod 'FBSDKLoginKit', inhibit_warnings: true
  pod 'Starscream', '~> 3.0.2'

end
